In [265]:

import numpy as np
from numpy.linalg import eig
from eig_projections import create_lda_classifier, create_pca_classifier

# examples

In [268]:

# training samples D = {D1,D2}

d1 = [[1,2], [-3,-1], [4,5], [-1,1]]
d2 = [[0,-2], [5,2], [-1,-4], [3,1]]
sample1 = [d1, d2]

d1 = [[12,7,3],[8,10,7],[10,11,9],[7,12,13],[11,9,10]]
d2 = [[1,4,5],[4,6,6],[1,7,5],[2,8,7],[3,2,5]]
sample2 = [d1, d2]


## PCA classifier

In [269]:
create_pca_classifier(sample1)


array([[ 1.75,  1.25],
       [-1.75, -2.25],
       [ 4.75,  4.25],
       [ 0.25, -0.25],
       [-0.75, -1.25],
       [ 3.75,  3.25],
       [-2.25, -2.75],
       [ 2.25,  1.75]])

In [270]:
create_pca_classifier(sample2)

array([[ 7.14168837,  8.64047176,  8.05617319],
       [ 8.22574945,  9.54885987,  8.97826948],
       [10.79366415, 11.70064191, 11.16252336],
       [11.495351  , 12.28861984, 11.75937428],
       [10.89249447, 11.7834567 , 11.24658789],
       [ 0.45894378,  3.04067135,  2.371868  ],
       [ 3.58543212,  5.66050972,  5.0312415 ],
       [ 1.8810962 ,  4.23236282,  3.5815429 ],
       [ 3.88328351,  5.91009405,  5.28459223],
       [ 0.64229695,  3.19431199,  2.52782718]])

## LDA classifier

In [271]:
create_lda_classifier(sample1)

array([[ -6.57436998,   7.21854456],
       [-10.45562454,  11.48009496],
       [ -8.19023923,   8.99274105],
       [-11.53287071,  12.66289262],
       [ 12.07149379, -13.25429145],
       [ 15.41412527, -16.92444302],
       [ 18.64586377, -20.47283601],
       [ 10.45562454, -11.48009496]])

In [272]:
create_lda_classifier(sample2)

array([[4.98841905, 2.53250175, 0.72444152],
       [4.39687713, 2.23218998, 0.63853504],
       [5.26984399, 2.6753745 , 0.76531137],
       [4.67351237, 2.37263111, 0.6787093 ],
       [5.31036188, 2.69594447, 0.77119557],
       [1.17206554, 0.59502981, 0.17021283],
       [2.47009376, 1.25400787, 0.35871856],
       [1.64722419, 0.83625655, 0.23921759],
       [2.20820831, 1.12105486, 0.32068633],
       [1.47925857, 0.75098441, 0.21482484]])