# Step 1

In [88]:
import numpy as np
from numpy.linalg import eig

In [89]:
# training samples D = {D1,D2}
d1 = [[12,7,3],[8,10,7],[10,11,9],[7,12,13],[11,9,10]]
d2 = [[1,4,5],[4,6,6],[1,7,5],[2,8,7],[3,2,5]]

d_original = np.array(d1+d2)

d = lambda x: [np.array([i]).transpose() for i in x]

d1 = d(d1)
d2 = d(d2)

In [92]:
m1, m2 = sum(d1)/len(d1), sum(d2)/len(d2)
m1, m2

(array([[9.6],
        [9.8],
        [8.4]]),
 array([[2.2],
        [5.4],
        [5.6]]))

In [93]:
# difference between x_k and mean vector
xk_m1 = [i-m1 for i in d1]
xk_m2 = [i-m2 for i in d2]
# xk_m1, xk_m2

In [94]:
Sk = lambda x: np.sum([i.dot(i.T) for i in x],0)
Sw = Sk(xk_m1) + Sk(xk_m2)
Sw

array([[ 24. , -15.8, -18.8],
       [-15.8,  38. ,  30.2],
       [-18.8,  30.2,  58.4]])

In [95]:
md = m1 - m2
Sb = np.dot(md,md.T)
Sb

array([[54.76, 32.56, 20.72],
       [32.56, 19.36, 12.32],
       [20.72, 12.32,  7.84]])

In [86]:
e_val, e_vec = eig(np.dot(Sw.T,Sb))
w = np.amax(e_vec,0)
w

array([0.73338223, 0.87338958, 0.28307939])

In [87]:
projection = d_original.dot(w)
projection

array([15.76355198, 16.58250938, 19.48882219, 19.29438264, 18.75850464,
        5.6423375 ,  9.87234274,  8.26250626, 10.43543684,  5.36232279])

In [99]:
n = len(projection)
class2_m = np.mean(projection)
class2_sd = np.sum([((i - class2_m)**2)/n for i in projection])

class2_m, class2_sd

(12.946271695855813, 28.659954925238885)

In [110]:
5/den

0.04185406231581448

In [112]:
den = np.sum([np.abs(x-1) for x in projection])
class1_m = -n/(2*den)
class1_d = -n/2*(np.sum([np.abs((i - class1_m)**2-1) for i in projection]))

class1_m, class1_d

(-0.04185406231581448, -9817.568281766009)